source 'https://github.com/CocoaPods/Specs.git'
target 'Example' do
    pod 'react-native-braintree-card', :path => '../node_modules/react-native-braintree-card'
    pod 'React', :path => '../node_modules/react-native'
end
